name: release

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    if: github.repository == 'frontier159/viem-tx-sim'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.18.0
          registry-url: https://registry.npmjs.org
      - run: corepack enable
      - uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
        with:
          version: nightly-7debd6d47628c5551837534aee507dbf552d5889
      - run: pnpm install --frozen-lockfile
      - name: create version PR or publish
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
